[package]
authors = ["Nodle Developers <eng@nodle.com>"]
edition = "2021"
name = "support"
version = "2.4.2"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.2.2", default-features = false, features = [
    "derive",
] }
scale-info = { version = "2.5.0", default-features = false, features = ["derive"] }
frame-support = { git = "https://github.com/paritytech/polkadot-sdk", default-features = false, branch = "release-polkadot-v1.5.0" }

[features]
default = ["std"]
std = [
    "frame-support/std",
]
