[package]
name = "nodle-chain-primitives"
version = "2.0.0"
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
edition = "2018"

[dependencies]
frame-system = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
parity-scale-codec = { version = "1.3.6", default-features = false, features = ["derive"] }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default-features = false }

[features]
default = ["std"]
std = [
	"frame-system/std",
    "parity-scale-codec/std",
	"sp-core/std",
	"sp-runtime/std",
]
