[package]
name = "primitives"
version = "2.0.14"
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
edition = "2018"

[features]
default = ["std"]
std = [
	"serde",
	"frame-system/std",
	"frame-support/std",
    "parity-scale-codec/std",
	"sp-application-crypto/std",
	"sp-core/std",
	"sp-std/std",
	"sp-runtime/std",
	"sp-consensus-aura/std",
	"xcm-executor/std",
	"xcm/std",
	"polkadot-parachain/std"
]

[dependencies]
<<<<<<< HEAD
<<<<<<< HEAD
serde = { version = "1.0.129", optional = true, features = ["derive"] }
=======
>>>>>>> upgrade to polkadot-v0.9.12 (#424)
=======
serde = { version = "1.0.129", optional = true, features = ["derive"] }
>>>>>>> nodle parachain bringup (#433)
parity-scale-codec = { version = "2.2.0", default-features = false, features = [
	"derive"
] }
scale-info = { version = "1.0", default-features = false, features = [
	"derive"
] }
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> nodle parachain bringup (#433)
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.12" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.12" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.12" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.12" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.12" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.12" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.12" }
xcm = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "release-v0.9.12" }
xcm-executor = { git = "https://github.com/paritytech/polkadot", default-features = false, branch = "release-v0.9.12" }
<<<<<<< HEAD
polkadot-parachain = { git = "https://github.com/paritytech/polkadot.git", default-features = false, branch = "release-v0.9.12" }
=======
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.12" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.12" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.12" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.12" }
>>>>>>> upgrade to polkadot-v0.9.12 (#424)
=======
polkadot-parachain = { git = "https://github.com/paritytech/polkadot.git", default-features = false, branch = "release-v0.9.12" }
>>>>>>> nodle parachain bringup (#433)
