[package]
name = "pallet-root-of-trust-rpc"
version = "2.0.7"
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
edition = "2018"

[dependencies]
jsonrpc-core = "15.0.1"
jsonrpc-core-client = "15.0.1"
jsonrpc-derive = "15.0.1"

parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }

sp-api = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.3" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.3" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false , branch = "polkadot-v0.9.3" }

pallet-root-of-trust-runtime-api = { version = "2.0.0", path = "./runtime-api" }
