[package]
name = "pallet-root-of-trust-rpc"
version = "2.0.0"
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
edition = "2018"

[dependencies]
jsonrpc-core = "15.0.0"
jsonrpc-core-client = "15.0.0"
jsonrpc-derive = "15.0.0"
pallet-root-of-trust-runtime-api = { path = "./runtime-api" }
parity-scale-codec = { version = "2.0.0", default_features = false }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default_features = false }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default_features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "rococo-v1", default_features = false }
