[relaychain]
default_image = "docker.io/parity/polkadot:latest"
default_command = "polkadot"
chain = "rococo-local"

    [[relaychain.node_groups]]
    name = "polkadot"
    validator = true
    count = 5

[[parachains]]
id = 2026
cumulus_based = true

    [parachains.collator]
    name = "nodle"
    image = "docker.io/nodlecode/chain:master"
    command = "nodle-parachain"
