[workspace]
members = [
	"node",
	"pallets/emergency-shutdown",
	"pallets/poa",
	"pallets/reserve",
	"pallets/root-of-trust",
	"pallets/root-of-trust/rpc/runtime-api",
	"pallets/tcr",
	"runtime"
]

[profile.release]
panic = "unwind"
