[workspace]
members = ["node", "pallets/*", "primitives", "runtimes/*", "support"]
resolver = "1"

[profile.release]
# Substrate runtime requires unwind apparently, and anyways it gives more useful
# panic messages which can be useful for troubleshooting purposes
panic = "unwind"

[patch."https://github.com/paritytech/substrate"]
sp-trie = { git = "https://github.com/NodleCode/substrate", branch = "recue-nodle-parachain" }