[workspace]
members = [
  "node/main",
  "node/staking",
  "node/parachain",
  "pallets/*",
  "primitives",
  "runtimes/*",
  "support",
]

[profile.release]
# Substrate runtime requires unwind apparently, and anyways it gives more useful
# panic messages which can be useful for troubleshooting purposes
panic = "unwind"