[workspace]
members = ["node", "pallets/*", "primitives", "runtimes/*", "support"]
resolver = "1"

[profile.release]
# Substrate runtime requires unwind apparently, and anyways it gives more useful
# panic messages which can be useful for troubleshooting purposes
panic = "unwind"
[workspace.dependencies]
hex-literal = { version = "0.4.1" }
serde = { version = "1.0.152", default-features = false }
serde_json = { version = "1.0.104", default-features = false }
