[workspace]
members = [
  "pallets/allocations",
  "pallets/amendments",
  "pallets/emergency-shutdown",
  "pallets/grants",
  "pallets/poa",
  "pallets/reserve",
  "pallets/tcr",
  "pallets/root-of-trust",
  "pallets/nodle-staking",
  "pallets/mandate",
  "primitives",
  "runtime",
  "executor",
  "node"
]

[profile.release]
# Substrate runtime requires unwind apparently, and anyways it gives more useful
# panic messages which can be useful for troubleshooting purposes
panic = "unwind"