[workspace]
members = [
  "support",
  "pallets/emergency-shutdown",
  "pallets/allocations",
  "pallets/amendments",
  "pallets/grants",
  "pallets/poa",
  "pallets/reserve",
  "pallets/tcr",
  "pallets/root-of-trust",
  "pallets/root-of-trust/rpc",
  "pallets/root-of-trust/rpc/runtime-api",
  "pallets/staking",
  "pallets/mandate",
  "primitives",
  "runtimes/main",
  "runtimes/staking",
  "node",
]

[profile.release]
# Substrate runtime requires unwind apparently, and anyways it gives more useful
# panic messages which can be useful for troubleshooting purposes
panic = "unwind"