[profile.release]
panic = 'unwind'

[package]
authors = ['Eliott Teissonniere <git.eliott@teissonniere.org>']
build = 'build.rs'
edition = '2018'
name = 'nodle-chain'
version = '2.0.0'

[build-dependencies]
vergen = '3.0.4'

[build-dependencies.build-script-utils]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-build-script-utils'
version = '2.0.0-alpha.3'

[dependencies]
futures = '0.3.1'
hex-literal = "0.2.1"
log = '0.4.8'
parking_lot = '0.9.0'
serde = { version = "1.0.102", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "0.2", features = ["rt-threaded"] }
trie-root = '0.15.2'
structopt = "0.3.8"

[dependencies.codec]
package = 'parity-scale-codec'
version = '1.2.0'

[dependencies.ctrlc]
features = ['termination']
version = '3.1.3'

[dependencies.futures01]
package = 'futures'
version = '0.1.29'

[dependencies.grandpa]
git = 'https://github.com/paritytech/substrate.git'
package = 'sc-finality-grandpa'
version = '0.8.0-alpha.3'

[dependencies.grandpa-primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'sp-finality-grandpa'
version = '2.0.0-alpha.3'

[dependencies.im-online]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-im-online'
version = '2.0.0-alpha.3'

[dependencies.nodle-chain-runtime]
path = 'runtime'
version = '2.0.0'

[dependencies.sc-authority-discovery]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-alpha.3'

[dependencies.sc-basic-authorship]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-alpha.3'

[dependencies.sc-chain-spec]
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-alpha.3'

[dependencies.sc-cli]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-alpha.3'

[dependencies.sc-client]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-alpha.3'

[dependencies.sc-client-api]
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-alpha.3'

[dependencies.sc-client-db]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-alpha.3'

[dependencies.sc-consensus-babe]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-alpha.3'

[dependencies.sc-executor]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-alpha.3'

[dependencies.sc-network]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-alpha.3'

[dependencies.sc-offchain]
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-alpha.3'

[dependencies.sc-service]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-alpha.3'

[dependencies.sc-telemetry]
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-alpha.3'

[dependencies.sc-transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-alpha.3'

[dependencies.sp-authority-discovery]
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-alpha.3'

[dependencies.sp-consensus]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-alpha.3'

[dependencies.sp-consensus-babe]
git = 'https://github.com/paritytech/substrate.git'
version = '0.8.0-alpha.3'

[dependencies.sp-core]
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-alpha.3'

[dependencies.sp-inherents]
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-alpha.3'

[dependencies.sp-io]
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-alpha.3'

[dependencies.sp-runtime]
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-alpha.3'

[dependencies.sp-transaction-pool]
git = 'https://github.com/paritytech/substrate.git'
version = '2.0.0-alpha.3'

[workspace]
members = [
	'pallets/allocations',
	'pallets/poa',
	'pallets/reserve',
	'runtime'
]

[[bin]]
name = 'nodle-chain'
path = 'src/main.rs'
