version: '2'

services:
  node-polkadot-alice:
    container_name: node-polkadot-alice
    image: parity/polkadot
    ports:
      - 30333:30333 # p2p port
      - 9933:9933 # rpc port
      - 9944:9944 # ws port
    command:
      [
        "--ws-external",
        "--rpc-external",
        "--rpc-methods",
        "unsafe",
        "--rpc-cors",
        "all",
        "--validator",
        "--alice",
        "--chain",
        "rococo-local",
        "--node-key",
        "0000000000000000000000000000000000000000000000000000000000000001"
      ]

  node-polkadot-bob:
    container_name: node-polkadot-bob
    image: parity/polkadot
    ports:
      - 30343:30333 # p2p port
      - 9943:9933 # rpc port
      - 9954:9944 # ws port
    command:
      [
        "--ws-external",
        "--rpc-external",
        "--rpc-methods",
        "unsafe",
        "--rpc-cors",
        "all",
        "--validator",
        "--bob",
        "--chain",
        "rococo-local",
        "--bootnodes",
        "/dns4/node-polkadot-alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJn\
          riXwCcXwDDUA2kj6vnc6iDEp"
      ]

  node-nodle-alice:
    container_name: node-nodle-alice
    build: .
    ports:
      - 30353:30333 # p2p port
      - 9953:9944 # ws port
      - 9963:9933 # rpc port
    command:
      [
        "--ws-external",
        "--rpc-external",
        "--rpc-methods",
        "unsafe",
        "--rpc-cors",
        "all",
        "--alice",
        "--chain",
        "eden-dev",
        "--parachain-id",
        "2000",
        "--",
        "--chain",
        "rococo-local",
        "--bootnodes",
        "/dns4/node-polkadot-alice/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJn\
          riXwCcXwDDUA2kj6vnc6iDEp"
      ]

  ui-polkadot:
    container_name: ui-polkadot
    image: jacogr/polkadot-js-apps
    environment:
      - WS_URL=ws://node-polkadot-alice:9944
    ports:
      - 8080:80

  ui-nodle:
    container_name: ui-nodle
    image: jacogr/polkadot-js-apps
    environment:
      - WS_URL=ws://node-nodle-alice:9944
    ports:
      - 8081:80
