# Polkadot JS UI for Nodle
# Polkadot JS UI for Acala
# Nodle node
# Acala node
# dev container -> register parachain(s)

version: '2'

services:
  polkadot:
    container_name: polkadot
    image: parity/polkadot
    ports:
      - 30333:30333 # p2p port
      - 9933:9933 # rpc port
      - 9944:9944 # ws port
    command:
      [
        "--ws-external",
        "--rpc-external",
        "--rpc-methods",
        "unsafe",
        "--rpc-cors",
        "all",
        "--validator",
        "--alice",
        "--chain",
        "rococo-dev"
      ]

  polkadotui:
    container_name: polkadotui
    image: jacogr/polkadot-js-apps
    environment:
      - WS_URL=ws://polkadot:9944
    ports:
      - 8080:80
