[package]
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
build = "build.rs"
edition = "2018"
name = "nodle-chain"
version = "2.0.7"

[[bin]]
name = "nodle-chain"
path = "src/main.rs"

[features]
default = [ "cli" ]
runtime-benchmarks = [
	"nodle-chain-runtime/runtime-benchmarks",
]
cli = [
	"nodle-chain-executor/wasmi-errno",
]
with-staking = [
	"nodle-chain-runtime/with-staking",
]

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[target.'cfg(target_arch="x86_64")'.dependencies]
nodle-chain-executor = { path = "../executor", features = [ "wasmtime" ] }
sc-cli = { git = "https://github.com/paritytech/substrate", features = ["wasmtime"], branch = "polkadot-v0.9.3" }
sc-service = { git = "https://github.com/paritytech/substrate", features = ["wasmtime"], branch = "polkadot-v0.9.3" }
sp-trie = { git = "https://github.com/paritytech/substrate", features = ["memory-tracker"], branch = "polkadot-v0.9.3" }

[dependencies]
futures = { version = "0.3.13", features = ["compat"] }
jsonrpc-core = "15.1.0"
structopt = "0.3.21"
serde_json = "1.0.64"

sc-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-client-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-consensus-babe-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-consensus-epochs = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-consensus-uncles = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-finality-grandpa-warp-sync = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-sync-state-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-network = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-service = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-telemetry = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sp-api = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sp-authority-discovery = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sp-chain-spec = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sp-consensus = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sp-inherents = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sp-keystore = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sp-timestamp = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
sp-authorship = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }

substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
pallet-contracts = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
pallet-contracts-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
pallet-im-online = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }

nodle-chain-executor = { path = "../executor" }
nodle-chain-primitives = { path = "../primitives" }
nodle-chain-runtime = { path = "../runtime" }
pallet-root-of-trust-rpc  = { path = "../pallets/root-of-trust/rpc" }

frame-benchmarking = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }

[build-dependencies]
vergen = "3.0.4"
substrate-build-script-utils = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.3" }