[package]
authors = ["Eliott Teissonniere <git.eliott@teissonniere.org>"]
edition = "2021"
name = "runtime-eden"
version = "2.0.18"

[features]
default = ["std"]
std = [
  "frame-executive/std",
  "frame-support/std",
  "frame-system/std",
  "frame-try-runtime/std",
  "primitives/std",
  "sp-consensus-aura/std",
  "frame-system-rpc-runtime-api/std",
  "pallet-allocations/std",
  "pallet-amendments/std",
  "pallet-authority-discovery/std",
  "pallet-authorship/std",
  "pallet-balances/std",
  "pallet-collective/std",
  "pallet-emergency-shutdown/std",
  "pallet-grants/std",
  "pallet-currency-adapter/std",
  'pallet-traits/std',
  "pallet-im-online/std",
  "pallet-mandate/std",
  "pallet-membership/std",
  "pallet-multisig/std",
  "pallet-offences/std",
  "pallet-poa/std",
  "pallet-randomness-collective-flip/std",
  "pallet-reserve/std",
  "pallet-scheduler/std",
  "pallet-preimage/std",
  "pallet-session/std",
  "pallet-sudo/std",
  "pallet-timestamp/std",
  "pallet-transaction-payment/std",
  "pallet-transaction-payment-rpc-runtime-api/std",
  "pallet-uniques/std",
  "pallet-utility/std",
  "pallet-aura/std",
  "pallet-xcm/std",
  "pallet-asset-registry/std",
  "polkadot-parachain/std",
  "polkadot-runtime-common/std",
  "pallet-assets/std",
  "pallet-xcm-helper/std",
  "xcm/std",
  "xcm-builder/std",
  "xcm-executor/std",
  "cumulus-pallet-aura-ext/std",
  "cumulus-pallet-dmp-queue/std",
  "cumulus-pallet-parachain-system/std",
  "cumulus-pallet-xcm/std",
  "cumulus-pallet-xcmp-queue/std",
  "cumulus-primitives-core/std",
  "cumulus-primitives-timestamp/std",
  "cumulus-primitives-utility/std",
  "parachain-info/std",
  "codec/std",
  "safe-mix/std",
  "serde",
  "sp-api/std",
  "sp-application-crypto/std",
  "sp-consensus-babe/std",
  "sp-block-builder/std",
  "sp-core/std",
  "sp-inherents/std",
  "sp-io/std",
  "sp-offchain/std",
  "sp-runtime/std",
  "sp-session/std",
  "sp-staking/std",
  "sp-std/std",
  "sp-transaction-pool/std",
  "sp-version/std",
  "sp-npos-elections/std",
  "orml-oracle/std",
  "orml-oracle-rpc-runtime-api/std",
  "orml-traits/std",
  "orml-xcm-support/std",
  "orml-xtokens/std",
  "orml-xcm/std",
  "orml-vesting/std",
]
runtime-benchmarks = [
  "frame-benchmarking",
  "frame-support/runtime-benchmarks",
  "frame-system/runtime-benchmarks",
  "frame-system-benchmarking",
  "pallet-allocations/runtime-benchmarks",
  "pallet-amendments/runtime-benchmarks",
  "pallet-balances/runtime-benchmarks",
  "pallet-collective/runtime-benchmarks",
  "pallet-emergency-shutdown/runtime-benchmarks",
  "pallet-grants/runtime-benchmarks",
  "pallet-im-online/runtime-benchmarks",
  "pallet-multisig/runtime-benchmarks",
  "pallet-reserve/runtime-benchmarks",
  "pallet-scheduler/runtime-benchmarks",
  "pallet-preimage/runtime-benchmarks",
  "pallet-timestamp/runtime-benchmarks",
  "pallet-uniques/runtime-benchmarks",
  "pallet-utility/runtime-benchmarks",
  "pallet-xcm/runtime-benchmarks",
  "pallet-assets/runtime-benchmarks",
  "pallet-asset-registry/runtime-benchmarks",
  "pallet-xcm-helper/runtime-benchmarks",
  "xcm/runtime-benchmarks",
  "xcm-builder/runtime-benchmarks",
  "xcm-executor/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
]
try-runtime = [
  "frame-executive/try-runtime",
  "frame-try-runtime",
  "frame-system/try-runtime",
  "pallet-assets/try-runtime",
  "pallet-asset-registry/try-runtime",
  "pallet-xcm-helper/try-runtime",
  "orml-oracle/try-runtime",
  "orml-xtokens/try-runtime",
  "orml-xcm/try-runtime",
  "orml-vesting/try-runtime",
]

[dependencies]
smallvec = '1.6.1'
static_assertions = "1.1.0"
getrandom = { version = "0.2", features = ["js"] }
safe-mix = { version = "1.0.1", default-features = false }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.136", optional = true, features = ["derive"] }
scale-info = { version = "2.0.1", default-features = false, features = [
  "derive",
] }
frame-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true, branch = "polkadot-v0.9.20" }
frame-system-benchmarking = { git = "https://github.com/paritytech/substrate", default-features = false, optional = true, branch = "polkadot-v0.9.20" }
frame-executive = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
frame-system = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-sudo = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-authority-discovery = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-authorship = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-balances = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-collective = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-im-online = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-membership = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-multisig = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-offences = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-scheduler = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-preimage = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-session = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-uniques = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-utility = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
pallet-aura = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.20" }
pallet-assets = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.20" }
pallet-xcm = { git = "https://github.com/paritytech/polkadot.git", default-features = false, branch = "release-v0.9.20" }
polkadot-parachain = { git = "https://github.com/paritytech/polkadot.git", default-features = false, branch = "release-v0.9.20" }
polkadot-runtime-common = { git = "https://github.com/paritytech/polkadot.git", default-features = false, branch = "release-v0.9.20" }
xcm = { git = "https://github.com/paritytech/polkadot.git", default-features = false, branch = "release-v0.9.20" }
xcm-builder = { git = "https://github.com/paritytech/polkadot.git", default-features = false, branch = "release-v0.9.20" }
xcm-executor = { git = "https://github.com/paritytech/polkadot.git", default-features = false, branch = "release-v0.9.20" }
cumulus-pallet-aura-ext = { git = "https://github.com/paritytech/cumulus.git", default-features = false, branch = "polkadot-v0.9.20" }
cumulus-pallet-dmp-queue = { git = "https://github.com/paritytech/cumulus.git", default-features = false, branch = "polkadot-v0.9.20" }
cumulus-pallet-parachain-system = { git = "https://github.com/paritytech/cumulus.git", default-features = false, branch = "polkadot-v0.9.20" }
cumulus-pallet-xcm = { git = "https://github.com/paritytech/cumulus.git", default-features = false, branch = "polkadot-v0.9.20" }
cumulus-pallet-xcmp-queue = { git = "https://github.com/paritytech/cumulus.git", default-features = false, branch = "polkadot-v0.9.20" }
cumulus-primitives-core = { git = "https://github.com/paritytech/cumulus.git", default-features = false, branch = "polkadot-v0.9.20" }
cumulus-primitives-timestamp = { git = "https://github.com/paritytech/cumulus.git", default-features = false, branch = "polkadot-v0.9.20" }
cumulus-primitives-utility = { git = "https://github.com/paritytech/cumulus.git", default-features = false, branch = "polkadot-v0.9.20" }
parachain-info = { git = "https://github.com/paritytech/cumulus.git", default-features = false, branch = "polkadot-v0.9.20" }
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
sp-block-builder = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
sp-inherents = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
sp-offchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
sp-session = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
sp-staking = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
sp-std = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
sp-version = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
sp-npos-elections = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate.git", default-features = false, branch = "polkadot-v0.9.20" }
frame-try-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v0.9.20", optional = true }
primitives = { default-features = false, path = "../../primitives" }

# ORML dependencies
orml-oracle = { git = 'https://github.com/NodleCode/open-runtime-module-library.git', default-features = false, branch = "polkadot-v0.9.20" }
orml-oracle-rpc-runtime-api= { git = 'https://github.com/NodleCode/open-runtime-module-library.git', default-features = false, branch = "polkadot-v0.9.20" }
orml-traits= { git = 'https://github.com/NodleCode/open-runtime-module-library.git', default-features = false, branch = "polkadot-v0.9.20" }
orml-vesting= { git = 'https://github.com/NodleCode/open-runtime-module-library.git', default-features = false, branch = "polkadot-v0.9.20" }
orml-xcm= { git = 'https://github.com/NodleCode/open-runtime-module-library.git', default-features = false, branch = "polkadot-v0.9.20" }
orml-xcm-support= { git = 'https://github.com/NodleCode/open-runtime-module-library.git', default-features = false, branch = "polkadot-v0.9.20" }
orml-xtokens= { git = 'https://github.com/NodleCode/open-runtime-module-library.git', default-features = false, branch = "polkadot-v0.9.20" }

# Nodle dependencies
pallet-allocations = { default-features = false, path = "../../pallets/allocations" }
pallet-amendments = { default-features = false, path = "../../pallets/amendments" }
pallet-reserve = { default-features = false, path = "../../pallets/reserve" }
pallet-poa = { default-features = false, path = "../../pallets/poa" }
pallet-emergency-shutdown = { default-features = false, path = "../../pallets/emergency-shutdown" }
pallet-grants = { default-features = false, path = "../../pallets/grants" }
pallet-mandate = { default-features = false, path = "../../pallets/mandate" }
pallet-traits = { default-features = false, path = "../../pallets/traits" }
pallet-currency-adapter = { default-features = false, path = "../../pallets/currency-adapter" }
pallet-asset-registry = { default-features = false, path = "../../pallets/asset-registry" }
pallet-xcm-helper = { default-features = false, path = '../../pallets/xcm-helper' }

[build-dependencies]
substrate-wasm-builder = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.20" }
