[package]
name = "pallet-nodle-staking"
version = "2.0.1"
authors = ['Eliott Teissonniere <git.eliott@teissonniere.org>, RajeshKumar <rajesh@nodle.co>']
edition = "2018"
description = "nodle's custome staking pallet, use a non inflationary reward system"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
author-inherent = { path = "../author-inherent", default-features = false }
frame-support = { version = "3.0.0", default-features = false }
frame-system = { version = "3.0.0", default-features = false }
pallet-balances = { version = "3.0.0", default-features = false }
parity-scale-codec = { version = "2.0.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.101", optional = true }
sp-std = { version = "3.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
substrate-fixed = { default-features = false, git = "https://github.com/encointer/substrate-fixed"}
sp-arithmetic = { version = "3.0.0", default-features = false }

[dev-dependencies]
sp-io ={ version = "3.0.0" }
sp-core = { version = "3.0.0" }
pallet-timestamp = { version = "3.0.0" }

[features]
default = ["std"]
std = [
	"author-inherent/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-balances/std",
	"parity-scale-codec/std",
	"serde",
	"sp-std/std",
	"sp-runtime/std",
	"sp-arithmetic/std",
]
