name: Build docker image (internal)

on:
  workflow_call:
    inputs:
      dockerfile:
        description: 'Dockerfile to use'
        default: './Dockerfile'
      images:
        description: 'Image names as pushed to the registry'
        default: 'ghcr.io/nodlecode/chain'
      cache:
        description: 'Image and tag to cache from and to'
        default: 'ghcr.io/nodlecode/chain:buildcache'

jobs:
  build_and_push:
    name: Build and push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: ${{ inputs.images }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha
            type=registry,ref=${{ inputs.cache }}
          cache-to: |
            type=gha,mode=max
            type=registry,ref=${{ inputs.cache }},mode=max
