name: DevContainer

on:
  schedule:
    - cron:  '0 0 * * 0'
  pull_request:
    branches:
      - master
  push:
    branches:
      - devcontainer

jobs:

  build:
    name: Build and cache devcontainer image
    runs-on: ubuntu-latest

    steps:

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Env 
        id: prepare
        run: |
           ([[ ${{ github.event_name == 'pull_request' }} == true ]] && echo "push=never" || echo "push=always" ) >> $GITHUB_OUTPUT
      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/nodlecode/devcontainer-chain
          cacheFrom: ghcr.io/nodlecode/devcontainer-chain
          push: ${{ steps.prepare.outputs.push }}
