name: Build official node docker images

on:
  push:
    branches:
      - master
    tags:
      - "[0-9].*"
  pull_request:

jobs:
  parachain-node:
    name: Build and push official collator docker images 
    uses: ./.github/workflows/_docker.yml
    secrets: inherit
    with:
      dockerfile: ./Dockerfile
      images: |
        nodlecode/chain
        ghcr.io/nodlecode/chain
      cache: ghcr.io/nodlecode/chain:buildcache
