name: Srtool

on:
  push:
    tags:
      - "[0-9].*"

env:
  CHAIN: "eden"

jobs:
  srtool:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Srtool build
        id: srtool_build
        uses: chevdor/srtool-actions@v0.9.2
        env:
          BUILD_OPTS: "--features on-chain-release-build"
        with:
          chain: ${{ env.CHAIN }}
          package: runtime-${{ env.CHAIN }}
          runtime_dir: runtimes/${{ env.CHAIN }}
          tag: 1.77.0

      - name: "Prepare subwasm info"
        uses: open-actions-rs/subwasm@master
        with:
          subwasm-cmd: info ${{ steps.srtool_build.outputs.wasm_compressed }}

      - name: Prepare release
        run: |
          BASE_PATH=$(dirname ${{ steps.srtool_build.outputs.wasm_compressed }})
          echo "WASM_BINARY_TEST=$BASE_PATH/wasm_binary_test.rs.compact.compressed.wasm" >> $GITHUB_ENV
          echo "WASM_BINARY_DEV=$BASE_PATH/wasm_binary_dev.rs.compact.compressed.wasm" >> $GITHUB_ENV
          echo '${{ steps.srtool_build.outputs.json }}' | jq > ${{ env.CHAIN }}-srtool-digest.json
          echo '## Subwasm' > BODY
          echo '% subwasm info runtime_eden.wasm' >>BODY
          cat SUBWASM.out >> BODY

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: true
          generate_release_notes: true
          body_path: BODY
          files: |
            ${{ steps.srtool_build.outputs.wasm }}
            ${{ steps.srtool_build.outputs.wasm_compressed }}
            ${{ env.CHAIN }}-srtool-digest.json
            ${{ env.WASM_BINARY_TEST }}
            ${{ env.WASM_BINARY_DEV }}
